version: '3.8'

services:
  bot:
    build: .
    container_name: juridic-concursos-bot
    env_file: .env
    volumes:
      - ./knowledge:/app/knowledge
      - ./.chroma:/app/.chroma
      - ./logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "python", "-c", "import psutil; exit(0 if psutil.cpu_percent() < 90 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data:
  logs: