site_name: Bot Jurídico Conversacional
site_description: Assistente jurídico inteligente para estudantes de concursos públicos brasileiros
site_author: Gabriel Ramos
site_url: https://prof-ramos.github.io/SamerPosterga

repo_name: prof-ramos/SamerPosterga
repo_url: https://github.com/prof-ramos/SamerPosterga
edit_uri: edit/main/docs/

# Configuração para GitHub Pages direto da pasta docs/
docs_dir: docs
site_dir: site
use_directory_urls: false

theme:
  name: material
  language: pt
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Alternar para modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Alternar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Alternar para preferência do sistema
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: prof-ramos/SamerPosterga
      branch: main

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: prof-ramos
      repo: SamerPosterga
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Início: index.md
  - Instalação:
      - Visão Geral: instalacao/index.md
      - Local: instalacao/local.md
  - Implantação:
      - Visão Geral: implantacao/index.md
      - VPS com Portainer: implantacao/vps-portainer.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prof-ramos/SamerPosterga
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/prof-ramos/juridic-bot
  generator: false

extra_css:
  - assets/stylesheets/extra.css

copyright: Copyright &copy; 2025 Gabriel Ramos - Bot Jurídico Conversacional